# Site
repository: douglasreis/douglasreis.github.io
# favicon: images/favicon.ico

# Personal info
name: Douglas Reis
title: Senior Full Stack Developer
email: douglas@douglasreis.co.uk
website: http://www.douglasreis.co.uk

# Social links
twitter_username: DougReis
github_username:  douglasreis
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: reisdouglas
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Doug and I'm a passionate Senior Full Stack Software Developer 🚀 having an experience of building multiple applications with .Net / Node.js / JavaScript / Python. Lately I have been involved in several projects in AWS and other tools such as CI/CD to enable other developers to deliver their products in a efficient and reliable manner. Those projects have instigated in me more interest to learn even more about cloud ☁️ development and infrastructure as code.
  
  I have worked in a number of companies gaining teamwork and leadership skills and in this path I've learnt a lot how to offer support to other people in their career development. This part of my job has been very gratifying in my journey. 🙌

  I am most skilled in: <mark>.Net</mark> and <mark>AWS services</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Traveling
   - Skiing
   - Motorcycles
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
